services:
  turnstile-solver:
    build:
      context: .
      dockerfile: ./Docker/Dockerfile
    container_name: turnstile-solver
    restart: unless-stopped
    ports:
      - "3389:3389"
      - "5000:5000"